import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync,readdirSync} from 'node:fs';
import app from './dist/server/index.js';
const sqlite=new DatabaseSync(':memory:');for(const f of readdirSync('drizzle').filter(f=>f.endsWith('.sql')).sort())sqlite.exec(readFileSync('drizzle/'+f,'utf8'));
const wrap=(sql,args=[])=>({bind(...a){return wrap(sql,a)},async all(){return {results:sqlite.prepare(sql).all(...args)}},async first(){return sqlite.prepare(sql).get(...args)||null},async run(){return {meta:{changes:Number(sqlite.prepare(sql).run(...args).changes)}}}});
const DB={prepare:wrap,async batch(s){sqlite.exec('BEGIN');try{const result=[];for(const q of s)result.push(await q.run());sqlite.exec('COMMIT');return result}catch(e){sqlite.exec('ROLLBACK');throw e}}};
const call=async(path,body,cookie='',origin='http://test')=>{const res=await app.fetch(new Request('http://test/api/'+path,{method:body?'POST':'GET',headers:{cookie,origin,...(body?{'content-type':'application/json'}:{})},...(body?{body:JSON.stringify(body)}:{})}),{DB});return {status:res.status,data:await res.json(),cookie:res.headers.get('set-cookie')?.split(';')[0]}};
assert.equal((await call('state')).status,401);
const sessions={};for(const role of ['admin','hr','manager','employee']){const r=await call('login',{email:role+'@demo.vn',password:'NhanSu@2026'});assert.equal(r.status,200);sessions[role]=r.cookie}
assert.equal((await call('state',null,sessions.admin)).data.data.employees.length,168);
const emp=(await call('state',null,sessions.employee)).data;assert.equal(emp.data.employees.length,1);assert.equal(emp.data.audit.length,0);assert.equal(emp.data.recruitment.length,0);assert.equal(emp.data.contracts[0].salary,undefined);
const mgr=(await call('state',null,sessions.manager)).data;assert(mgr.data.employees.every(e=>e.id==='NV002'||e.managerId==='NV002'));
assert.equal((await call('save',{kind:'employees',record:{name:'Không được sửa'}},sessions.employee)).status,403);
assert.equal((await call('save',{kind:'departments',record:{name:'Không được sửa'}},sessions.manager)).status,403);
assert.equal((await call('approve',{id:'NP0',status:'Đã duyệt'},sessions.employee)).status,403);
assert.equal((await call('approve',{id:'NP0',status:'Đã duyệt'},sessions.manager)).status,403);
assert.equal((await call('approve',{id:'NP1',status:'Đã duyệt'},sessions.manager)).status,200);
assert.equal((await call('approve',{id:'NP1',status:'Đã duyệt'},sessions.manager)).status,409);
assert.equal((await call('save',{kind:'departments',record:{name:'Sai origin'}},sessions.admin,'http://evil')).status,403);
assert.equal((await call('save',{kind:'leaves',record:{employeeId:'NV008',start:'2026-11-02',end:'2026-11-03',type:'Nghỉ phép năm',reason:'Kiểm thử nghỉ phép'}},sessions.employee)).status,200);
const leave=(await call('state',null,sessions.employee)).data.data.leaves.find(l=>l.reason==='Kiểm thử nghỉ phép');assert.equal(leave.employeeId,'NV007');assert.equal(leave.status,'Chờ duyệt');
assert.equal((await call('save',{kind:'leaves',record:{start:'2026-11-03',end:'2026-11-04',type:'Nghỉ phép năm',reason:'Trùng lịch'}},sessions.employee)).status,400);
assert.equal((await call('approve',{id:leave.id,status:'Đã duyệt'},sessions.hr)).status,200);
assert.equal((await call('import',{kind:'departments',rows:[{name:'Kiểm thử Excel'}]},sessions.hr)).status,200);
assert((await call('state',null,sessions.admin)).data.data.departments.some(r=>r.name==='Kiểm thử Excel'));
assert.equal((await call('save',{kind:'contracts',record:{employeeId:'NV007',number:'TEST',start:'2026-12-01',end:'2026-01-01'}},sessions.hr)).status,400);
assert.equal((await call('logout',{},sessions.employee)).status,200);assert.equal((await call('state',null,sessions.employee)).status,401);
console.log('PASS: đăng nhập 4 vai trò, giới hạn dữ liệu, API phân quyền, CSRF, gửi/duyệt nghỉ phép, trùng lịch, nhập Excel, ngày hợp đồng, đăng xuất.');
