import html from '../generated-html.js';
import {aiRoute} from './ai.js';
const json=(v,status=200,extra={})=>new Response(JSON.stringify(v),{status,headers:{'content-type':'application/json;charset=utf-8','cache-control':'no-store',...extra}});
const fail=(message,status=400)=>{throw Object.assign(new Error(message),{status})};
const now=()=>new Date().toISOString();
const today=()=>new Date().toLocaleDateString('en-CA',{timeZone:'Asia/Ho_Chi_Minh'});
const hex=b=>Array.from(new Uint8Array(b),x=>x.toString(16).padStart(2,'0')).join('');
async function hash(password,salt){const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(password),'PBKDF2',false,['deriveBits']);return hex(await crypto.subtle.deriveBits({name:'PBKDF2',salt:new TextEncoder().encode(salt),iterations:100000,hash:'SHA-256'},key,256))}
const query=(db,sql,...args)=>db.prepare(sql).bind(...args);
async function all(db,kind){return (await query(db,'SELECT id,data FROM records WHERE kind=?',kind).all()).results.map(x=>({...JSON.parse(x.data),id:x.id}))}
const privileged=u=>['admin','hr'].includes(u.role);
const write=(db,kind,r)=>query(db,'INSERT INTO records(id,kind,data) VALUES(?,?,?) ON CONFLICT(id) DO UPDATE SET data=excluded.data',r.id,kind,JSON.stringify(r));
const log=(db,u,action)=>query(db,'INSERT INTO audit(id,actor,action,at) VALUES(?,?,?,?)',crypto.randomUUID(),u.name,action,now());
const fields={employees:['name','email','phone','department','title','start','status','gender','birth','address','managerId','balance'],departments:['name','head','description'],titles:['name','department','description'],contracts:['employeeId','number','type','start','end','salary','status'],attendance:['employeeId','date','checkIn','checkOut','status'],leaves:['employeeId','start','end','type','reason','status'],recruitment:['name','email','phone','position','department','stage','note']};
async function seed(db){if(await query(db,'SELECT id FROM users LIMIT 1').first())return;
 const depts=['Công nghệ','Kinh doanh','Nhân sự','Marketing','Tài chính','Vận hành'];const names=['Nguyễn Minh Anh','Trần Hoàng Nam','Lê Thu Hà','Phạm Đức Huy','Hoàng Ngọc Linh','Vũ Quang Hải','Đặng Thảo Vy','Bùi Anh Tuấn','Đỗ Minh Trang','Ngô Thanh Tùng','Dương Mỹ Linh','Nguyễn Quốc Bảo','Trần Khánh Chi','Lê Gia Hưng','Phạm Nhật Minh','Hoàng Thanh Mai'];
 const records=[];depts.forEach((name,i)=>records.push(['departments',{id:'d'+i,name,head:names[i],description:'Phòng '+name}]));
 ['Trưởng phòng','Chuyên viên','Nhân viên','Thực tập sinh'].forEach((name,i)=>records.push(['titles',{id:'t'+i,name,department:depts[i],description:''}]));
 for(let i=0;i<168;i++){const id='NV'+String(i+1).padStart(3,'0');const department=depts[i%6];records.push(['employees',{id,name:i<16?names[i]:names[i%16].replace(/ /,' '+['Văn','Thị','Hữu','Ngọc'][Math.floor(i/16)%4]+' '),email:'nv'+(i+1)+'@minhphat.vn',phone:'090'+String(1000000+i),department,title:i<6?'Trưởng phòng':i%9===0?'Chuyên viên cao cấp':'Chuyên viên',start:'202'+(i%4+2)+'-0'+(i%9+1)+'-05',status:i%23===0?'Thử việc':i%31===0?'Đã nghỉ việc':'Đang làm việc',gender:i%2?'Nam':'Nữ',birth:'1995-06-15',address:'TP. Hồ Chí Minh',managerId:'NV'+String(i%6+1).padStart(3,'0'),balance:12}]);records.push(['contracts',{id:'HD'+(i+1),employeeId:id,number:'HĐ/2026/'+String(i+1).padStart(3,'0'),type:'Xác định thời hạn',start:'2025-11-01',end:i<8?'2026-10-'+String(16+i):'2027-11-01',salary:15000000+i*100000,status:'Hiệu lực'}]);records.push(['attendance',{id:'CC'+(i+1),employeeId:id,date:today(),checkIn:i%8===0?'08:45':'08:00',checkOut:'17:30',status:i%8===0?'Đi muộn':'Đủ công'}])}
 for(let i=0;i<9;i++)records.push(['leaves',{id:'NP'+i,employeeId:'NV'+String(i+7).padStart(3,'0'),start:'2026-10-'+String(12+i),end:'2026-10-'+String(12+i),type:'Nghỉ phép năm',reason:['Việc gia đình','Nghỉ ngơi','Khám sức khỏe'][i%3],status:i<5?'Chờ duyệt':i<8?'Đã duyệt':'Từ chối'}]);
 ['Nguyễn Hải Yến','Trần Minh Khang','Lê Phương Anh','Vũ Thành Long','Đỗ Gia Bảo','Bùi Thùy Dương'].forEach((name,i)=>records.push(['recruitment',{id:'UV'+i,name,email:'ungvien'+i+'@gmail.com',phone:'0912345678',position:['Frontend Developer','Chuyên viên kinh doanh','HR Executive'][i%3],department:depts[i%3],stage:['Tiếp nhận','Sàng lọc','Phỏng vấn','Đề nghị','Trúng tuyển'][i%5],note:''}]));
 const statements=records.map(([k,r])=>write(db,k,r));for(const [role,name,employeeId] of [['admin','Nguyễn Minh Anh','NV001'],['hr','Lê Thu Hà','NV003'],['manager','Trần Hoàng Nam','NV002'],['employee','Đặng Thảo Vy','NV007']]){const salt=crypto.randomUUID();statements.push(query(db,'INSERT OR IGNORE INTO users(id,email,name,role,employee_id,salt,hash) VALUES(?,?,?,?,?,?,?)',role,role+'@demo.vn',name,role,employeeId,salt,await hash('NhanSu@2026',salt)))}
 statements.push(log(db,{name:'Hệ thống'},'Khởi tạo dữ liệu mẫu cho 168 nhân viên'));for(let i=0;i<statements.length;i+=80)await db.batch(statements.slice(i,i+80));
}
function days(start,end){let count=0;for(let d=new Date(start+'T00:00:00Z');d<=new Date(end+'T00:00:00Z');d.setUTCDate(d.getUTCDate()+1))if(![0,6].includes(d.getUTCDay()))count++;return count}
function validate(k,r){
const enums={employees:{status:['Đang làm việc','Thử việc','Đã nghỉ việc'],gender:['Nam','Nữ','Khác']},contracts:{status:['Hiệu lực','Hết hạn','Chấm dứt'],type:['Xác định thời hạn','Không xác định thời hạn','Thử việc']},attendance:{status:['Đủ công','Đi muộn','Vắng mặt','Nghỉ phép']},leaves:{status:['Chờ duyệt','Đã duyệt','Từ chối'],type:['Nghỉ phép năm','Nghỉ không lương','Nghỉ ốm']},recruitment:{stage:['Tiếp nhận','Sàng lọc','Phỏng vấn','Đề nghị','Trúng tuyển']}};
for(const [f,options] of Object.entries(enums[k]||{}))if(!options.includes(r[f]))fail('Giá trị '+f+' không hợp lệ');
if(k==='leaves'&&r.type==='Nghỉ phép năm'&&r.start?.slice(0,4)!==r.end?.slice(0,4))fail('Vui lòng tách yêu cầu phép năm theo từng năm');
if(k==='attendance')for(const t of ['checkIn','checkOut'])if(r[t]&&!/^([01]\d|2[0-3]):[0-5]\d$/.test(r[t]))fail('Giờ chấm công không hợp lệ');
for(const f of fields[k])if(typeof r[f]==='string'&&r[f].length>1000)fail('Nội dung quá dài');if(['employees','departments','titles','recruitment'].includes(k)&&!r.name?.trim())fail('Vui lòng nhập họ tên hoặc tên');if(r.email&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(r.email))fail('Email không hợp lệ');for(const f of ['start','end','date','birth'])if(r[f]&&(!/^\d{4}-\d{2}-\d{2}$/.test(r[f])||isNaN(Date.parse(r[f]))))fail('Ngày không hợp lệ');if(r.start&&r.end&&r.end<r.start)fail('Ngày kết thúc phải sau ngày bắt đầu');if(k==='contracts'&&(!r.start||!r.end||!r.number))fail('Nhập số hợp đồng và thời hạn');if(k==='attendance'&&!r.date)fail('Vui lòng chọn ngày');if(k==='leaves'&&(!r.start||!r.end||!r.reason?.trim()||days(r.start,r.end)<1||days(r.start,r.end)>60))fail('Nhập lý do và khoảng nghỉ từ 1–60 ngày làm việc');if(r.salary!==undefined&&(!Number.isFinite(Number(r.salary))||Number(r.salary)<0))fail('Mức lương không hợp lệ');if(r.balance!==undefined&&(!Number.isFinite(Number(r.balance))||Number(r.balance)<0))fail('Số ngày phép không hợp lệ')}
export default {async fetch(req,env){try{const url=new URL(req.url);const db=env.DB;if(!url.pathname.startsWith('/api/'))return new Response(html,{headers:{'content-type':'text/html;charset=utf-8','content-security-policy':"default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data:; connect-src 'self'; base-uri 'self'; form-action 'self'",'x-content-type-options':'nosniff','referrer-policy':'same-origin'}});
if(!db)fail('Cơ sở dữ liệu chưa được cấu hình',503);
if(req.method!=='GET'){const origin=req.headers.get('origin');if(origin&&origin!==url.origin)fail('Nguồn truy cập không hợp lệ',403);if(req.headers.get('content-type')!=='application/json')fail('Yêu cầu không hợp lệ',415)}
if(env.DEMO_MODE !== 'false')await seed(db);
const body=req.method==='GET'?{}:await req.json();if(JSON.stringify(body).length>250000)fail('Dữ liệu quá lớn',413);
const cookie=req.headers.get('cookie')?.match(/(?:^|; )hr_session=([^;]+)/)?.[1];const token=cookie?hex(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(cookie))):'';
const u=token?await query(db,'SELECT u.id,u.email,u.name,u.role,u.employee_id as employeeId FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token=? AND s.expires>?',token,Date.now()).first():null;
const cookieHeader=v=>`hr_session=${v}; HttpOnly; SameSite=Strict; Path=/; Max-Age=${v?28800:0}${url.protocol==='https:'?'; Secure':''}`;
if(url.pathname==='/api/login'){const email=String(body.email||'').toLowerCase();const key=(req.headers.get('cf-connecting-ip')||'local')+':'+email;const attempt=await query(db,'SELECT * FROM attempts WHERE key=?',key).first();if(attempt&&attempt.until>Date.now()&&attempt.count>=8)fail('Thử lại sau 15 phút',429);const user=await query(db,'SELECT * FROM users WHERE email=?',email).first();if(!user||await hash(String(body.password||''),user.salt)!==user.hash){await query(db,'INSERT INTO attempts(key,count,until) VALUES(?,1,?) ON CONFLICT(key) DO UPDATE SET count=CASE WHEN until<? THEN 1 ELSE count+1 END,until=excluded.until',key,Date.now()+900000,Date.now()).run();fail('Email hoặc mật khẩu không đúng',401)}const value=crypto.randomUUID()+crypto.randomUUID();const t=hex(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(value)));await db.batch([query(db,'DELETE FROM attempts WHERE key=?',key),query(db,'INSERT INTO sessions(token,user_id,expires) VALUES(?,?,?)',t,user.id,Date.now()+28800000),log(db,user,'Đăng nhập')]);return json({ok:true},200,{'set-cookie':cookieHeader(value)})}
if(!u)fail('Vui lòng đăng nhập',401);
if(url.pathname.startsWith('/api/ai/'))return json(await aiRoute(req,env,u,body,today()));
if(url.pathname==='/api/users'){if(u.role!=='admin')fail('Chỉ Admin được quản lý tài khoản',403);if(req.method==='GET')return json((await query(db,'SELECT id,name,email,role,employee_id as employeeId FROM users').all()).results);const roles=['admin','hr','manager','employee'];if(!roles.includes(body.role)||!body.name?.trim()||!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(body.email||'')||String(body.password||'').length<12)fail('Nhập tên, email, vai trò và mật khẩu ít nhất 12 ký tự');if(!await query(db,"SELECT id FROM records WHERE id=? AND kind='employees'",body.employeeId).first())fail('Mã hồ sơ nhân viên không tồn tại');if(await query(db,'SELECT id FROM users WHERE email=?',body.email.toLowerCase()).first())fail('Email tài khoản đã tồn tại');const salt=crypto.randomUUID();await db.batch([query(db,'INSERT INTO users(id,email,name,role,employee_id,salt,hash) VALUES(?,?,?,?,?,?,?)',crypto.randomUUID(),body.email.toLowerCase(),body.name,body.role,body.employeeId,salt,await hash(body.password,salt)),log(db,u,'Tạo tài khoản '+body.email+' · '+body.role)]);return json({ok:true})}
if(url.pathname==='/api/logout'){await query(db,'DELETE FROM sessions WHERE token=?',token).run();return json({ok:true},200,{'set-cookie':cookieHeader('')})}
if(url.pathname==='/api/password'){const user=await query(db,'SELECT * FROM users WHERE id=?',u.id).first();if(await hash(body.current||'',user.salt)!==user.hash)fail('Mật khẩu hiện tại không đúng');if(!body.password||body.password.length<12)fail('Mật khẩu mới cần ít nhất 12 ký tự');await db.batch([query(db,'UPDATE users SET hash=? WHERE id=?',await hash(body.password,user.salt),u.id),query(db,'DELETE FROM sessions WHERE user_id=?',u.id),log(db,u,'Đổi mật khẩu')]);return json({ok:true},200,{'set-cookie':cookieHeader('')})}
const employees=await all(db,'employees');const scoped=employees.filter(e=>privileged(u)||e.id===u.employeeId||(u.role==='manager'&&e.managerId===u.employeeId));const ids=new Set(scoped.map(e=>e.id));
if(url.pathname==='/api/state'){const data={};for(const k of Object.keys(fields)){let rows=k==='employees'?scoped:await all(db,k);if(['contracts','attendance','leaves'].includes(k))rows=rows.filter(r=>ids.has(r.employeeId));if(k==='contracts'&&!privileged(u))rows=rows.map(({salary,...rest})=>rest);if(k==='recruitment'&&!privileged(u))rows=[];data[k]=rows}data.audit=privileged(u)?(await query(db,'SELECT * FROM audit ORDER BY at DESC LIMIT 100').all()).results:[];return json({user:u,data,today:today(),demo:env.DEMO_MODE !== 'false'})}
if(url.pathname==='/api/approve'){const r=(await all(db,'leaves')).find(x=>x.id===body.id);if(!r)fail('Không tìm thấy yêu cầu',404);const e=employees.find(e=>e.id===r.employeeId);if(!(privileged(u)||(u.role==='manager'&&e?.managerId===u.employeeId&&e.id!==u.employeeId)))fail('Bạn không có quyền duyệt yêu cầu này',403);if(!['Đã duyệt','Từ chối'].includes(body.status))fail('Trạng thái không hợp lệ');if(r.status!=='Chờ duyệt')fail('Yêu cầu đã được xử lý',409);if(body.status==='Đã duyệt'){const used=(await all(db,'leaves')).filter(x=>x.employeeId===e.id&&x.status==='Đã duyệt'&&x.type==='Nghỉ phép năm'&&x.start.slice(0,4)===r.start.slice(0,4)).reduce((n,x)=>n+days(x.start,x.end),0);if(r.type==='Nghỉ phép năm'&&used+days(r.start,r.end)>Number(e.balance))fail('Không đủ ngày phép còn lại')}
const updated={...r,days:days(r.start,r.end),status:body.status,reviewer:u.name};const result=await db.batch([query(db,"UPDATE records SET data=? WHERE id=? AND kind='leaves' AND json_extract(data,'$.status')='Chờ duyệt' AND (?<>'Đã duyệt' OR json_extract(data,'$.type')<>'Nghỉ phép năm' OR (COALESCE((SELECT SUM(COALESCE(json_extract(l.data,'$.days'),1)) FROM records l WHERE l.kind='leaves' AND json_extract(l.data,'$.employeeId')=json_extract(records.data,'$.employeeId') AND json_extract(l.data,'$.status')='Đã duyệt' AND json_extract(l.data,'$.type')='Nghỉ phép năm' AND substr(json_extract(l.data,'$.start'),1,4)=substr(json_extract(records.data,'$.start'),1,4)),0)+?)<=CAST((SELECT json_extract(e.data,'$.balance') FROM records e WHERE e.id=json_extract(records.data,'$.employeeId')) AS REAL))",JSON.stringify(updated),r.id,body.status,updated.days),log(db,u,body.status+' yêu cầu '+r.id)]);if(!result[0].meta.changes)fail('Yêu cầu vừa được xử lý bởi người khác',409);return json({ok:true})}
if(url.pathname==='/api/save'||url.pathname==='/api/import'){const k=body.kind;if(!fields[k])fail('Loại dữ liệu không hợp lệ');if(!privileged(u)&&k!=='leaves')fail('Bạn không có quyền sửa dữ liệu này',403);if(url.pathname==='/api/import'&&!privileged(u))fail('Bạn không có quyền nhập dữ liệu',403);const input=url.pathname==='/api/import'?body.rows:[body.record];if(!Array.isArray(input)||input.length>300)fail('Mỗi lần nhập tối đa 300 dòng');const existing=await all(db,k);const stmts=[];for(const item of input){const prior=existing.find(x=>x.id===item.id);const r={id:prior?.id||crypto.randomUUID()};for(const f of fields[k])r[f]=item[f]??prior?.[f]??'';if(!privileged(u)&&k==='leaves'){if(prior)fail('Chỉ được tạo yêu cầu mới',403);r.employeeId=u.employeeId}if(k==='leaves'){r.status=prior?.status||'Chờ duyệt';if(prior?.status&&prior.status!=='Chờ duyệt')fail('Không sửa yêu cầu đã được xử lý');if(!prior){const overlaps=existing.some(x=>x.employeeId===r.employeeId&&x.status!=='Từ chối'&&x.start<=r.end&&x.end>=r.start);if(overlaps)fail('Khoảng nghỉ trùng yêu cầu đã có')}}if(['contracts','attendance','leaves'].includes(k)&&!employees.some(e=>e.id===r.employeeId))fail('Nhân viên không tồn tại');if(k==='employees'){if(!r.department||!r.title)fail('Chọn phòng ban và chức danh');if(existing.some(e=>e.email===r.email&&e.id!==r.id))fail('Email đã tồn tại');if(r.managerId&&!employees.some(e=>e.id===r.managerId))fail('Người quản lý không tồn tại')}
validate(k,r);
if(k==='leaves'){r.days=days(r.start,r.end);const condition=prior?'id<>?':'id<>?';stmts.push(query(db,`INSERT INTO records(id,kind,data) SELECT ?,?,? WHERE NOT EXISTS(SELECT 1 FROM records WHERE kind='leaves' AND ${condition} AND json_extract(data,'$.employeeId')=? AND json_extract(data,'$.status')<>'Từ chối' AND json_extract(data,'$.start')<=? AND json_extract(data,'$.end')>=?) ON CONFLICT(id) DO UPDATE SET data=excluded.data`,r.id,k,JSON.stringify(r),r.id,r.employeeId,r.end,r.start));}
else stmts.push(write(db,k,r));
if(prior&&prior.name!==r.name&&['departments','titles'].includes(k)){const field=k==='departments'?'department':'title';stmts.push(query(db,`UPDATE records SET data=json_set(data,'$.${field}',?) WHERE json_extract(data,'$.${field}')=?`,r.name,prior.name))}
}stmts.push(log(db,u,(url.pathname==='/api/import'?'Nhập Excel '+input.length+' dòng: ':'Lưu: ')+k));const saved=await db.batch(stmts);if(k==='leaves'&&saved.slice(0,input.length).some(x=>!x.meta.changes))fail('Yêu cầu trùng lịch đã tồn tại',409);return json({ok:true,count:input.length})}
fail('Không tìm thấy chức năng',404);
}catch(e){if(!e.status)console.error(e);return json({error:e.status?e.message:'Không thể xử lý dữ liệu. Vui lòng thử lại.'},e.status||500)}}};

